source 'https://rubygems.org'

gem 'asciidoctor-revealjs' # latest released version
gem 'asciidoctor-pdf'
gem 'rouge'
gem 'asciidoctor-diagram'
gem 'coderay'
gem 'asciidoctor-mathematical'
gem 'asciidoctor-epub3'
